/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import { Book, UserProfile, Order } from "./types";

export const CURATED_COLLECTIONS = [
  {
    id: "limited-editions",
    name: "Archival Series & Limited Editions",
    tagline: "Custom linen-bound spines, numbered prints, and certified editorial monographs.",
    description: "Crafted on premium heavyweight acid-free cotton paper, these objects are designed to withstand generations of tactile study.",
  },
  {
    id: "philosophical-inquiry",
    name: "Philosophical Inquiry",
    tagline: "Exploring the intersections of geometric reason, ethics, and modern existential forms.",
    description: "A series of critical editions detailing human ontology, modern aesthetics, and architectural philosophy.",
  },
];

export const BOOKS: Book[] = [
  {
    id: "warren-buffett",
    title: "Warren Buffett",
    subtitle: "The Snowball and the Business of Life",
    author: "Alice Schroeder",
    category: "Business",
    price: 25.00,
    publishDate: "September 2008",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400",
    isbn: "978-0553805093",
    pages: 976,
    binding: "Softcover",
    publisher: "Bantam",
    dimensions: "15.0 x 23.0 cm",
    rating: 4.8,
    featured: false,
    description: "Born in Nebraska in 1930, Warren Buffett demonstrated keen business abilities at a young age. He formed Buffett Partnership Ltd. in 1956, and by 1965 he had assumed control of Berkshire Hathaway.",
    authorBio: "Alice Schroeder is an American writer and former insurance analyst. She was selected by Warren Buffett to write his official biography.",
    specifications: { "Format": "Paperback" },
    reviews: []
  },
  {
    id: "true-experiment",
    title: "True experiment",
    subtitle: "The Story of My Experiments with Truth",
    author: "Mahatma Gandhi",
    category: "History",
    price: 12.99,
    publishDate: "1927",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=400",
    isbn: "978-0807059098",
    pages: 560,
    binding: "Softcover",
    publisher: "Beacon Press",
    dimensions: "13.0 x 20.0 cm",
    rating: 4.9,
    featured: false,
    description: "Born and raised in a Hindu merchant caste family in coastal Gujarat, India, and trained in law at the Inner Temple, London, Gandhi led peaceful campaigns for India's independence.",
    authorBio: "Mahatma Gandhi was an Indian lawyer, anti-colonial nationalist and political ethicist who employed nonviolent resistance.",
    specifications: { "Format": "Paperback" },
    reviews: []
  },
  {
    id: "charlotte-web",
    title: "Charlotte's Web",
    subtitle: "A Children's Classic",
    author: "E. B. White",
    category: "Fiction",
    price: 9.99,
    publishDate: "October 1952",
    coverImage: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400",
    isbn: "978-0064400558",
    pages: 192,
    binding: "Softcover",
    publisher: "HarperCollins",
    dimensions: "13.0 x 19.0 cm",
    rating: 4.7,
    featured: false,
    description: "Charlotte's Web is a children's novel by American author E. B. White and illustrated by Garth Williams; it was published on October 15, 1952.",
    authorBio: "Elwyn Brooks White was an American writer, philosopher, and co-author of the English language style guide The Elements of Style.",
    specifications: { "Format": "Paperback" },
    reviews: []
  },
  {
    id: "dhoni-touch",
    title: "The Dhoni Touch",
    subtitle: "Unraveling the Enigma that is Mahendra Singh Dhoni",
    author: "Bharat Sundaresan",
    category: "Sports",
    price: 15.99,
    publishDate: "July 2018",
    coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400",
    isbn: "978-9387894174",
    pages: 208,
    binding: "Softcover",
    publisher: "Penguin Random House",
    dimensions: "13.0 x 20.0 cm",
    rating: 4.6,
    featured: false,
    description: "For over a decade, Mahendra Singh Dhoni has captivated the world of cricket and billions of Indians with his incredible mental strength, calm under-pressure demeanor.",
    authorBio: "Bharat Sundaresan is a world-renowned cricket writer and reporter, known for his deep insights into player psyches.",
    specifications: { "Format": "Paperback" },
    reviews: []
  },
  {
    id: "sky-runner",
    title: "Sky Runner",
    subtitle: "Finding Strength, Happiness, and Balance in the Mountains",
    author: "Emelie Forsberg",
    category: "Sports",
    price: 22.00,
    publishDate: "May 2018",
    coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=400",
    isbn: "978-1937715830",
    pages: 176,
    binding: "Hardcover",
    publisher: "VeloPress",
    dimensions: "18.0 x 23.0 cm",
    rating: 4.8,
    featured: false,
    description: "Emelie Forsberg is a renown Sky runner recognised worldwide for her incredible strength, endurance and break neck speed down absolute mountain precipices.",
    authorBio: "Emelie Forsberg is a Swedish athlete who competes in trail running and ski mountaineering.",
    specifications: { "Format": "Hardback" },
    reviews: []
  },
  {
    id: "nelson-mandela",
    title: "Nelson Mandela",
    subtitle: "Long Walk to Freedom",
    author: "Nelson Mandela",
    category: "History",
    price: 18.99,
    publishDate: "December 1994",
    coverImage: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400",
    isbn: "978-0316548182",
    pages: 656,
    binding: "Softcover",
    publisher: "Little, Brown",
    dimensions: "14.0 x 21.0 cm",
    rating: 4.9,
    featured: false,
    description: "Nelson Rolihlahla Mandela (18 July 1918 – 5 December 2013) was a South African anti-apartheid politician and activist. On April 27, 1994, he became first black president of South Africa.",
    authorBio: "Nelson Mandela was a South African anti-apartheid revolutionary, political leader and philanthropist who served as President of South Africa from 1994 to 1999.",
    specifications: { "Format": "Paperback" },
    reviews: []
  },
  {
    id: "psychology-of-money",
    title: "The Psychology of Money",
    subtitle: "Timeless lessons on wealth, greed, and happiness",
    author: "Morgan Housel",
    category: "Business",
    price: 20.15,
    publishDate: "September 2020",
    coverImage: "https://images.unsplash.com/photo-1592492159418-09f31333cd83?auto=format&fit=crop&q=80&w=400",
    isbn: "978-0-85719-768-9",
    pages: 256,
    binding: "Softcover",
    publisher: "Harriman House",
    dimensions: "14.0 x 21.6 cm",
    rating: 4.8,
    featured: true,
    bgAccent: "#4a6b5d",
    description: "Doing well with money isn’t necessarily about what you know. It’s about how you behave. And behavior is hard to teach, even to really smart people.",
    authorBio: "Morgan Housel is a partner at Collaborative Fund and a former columnist at The Motley Fool and The Wall Street Journal.",
    specifications: {
      "Format": "Paperback",
      "Print Run": "Twentieth impressions"
    },
    reviews: []
  },
  {
    id: "how-innovation-works",
    title: "How Innovation Works",
    subtitle: "And Why It Flourishes in Freedom",
    author: "Matt Ridley",
    category: "Business",
    price: 24.99,
    publishDate: "May 2020",
    coverImage: "https://images.unsplash.com/photo-1589829085413-56de8ae18c73?auto=format&fit=crop&q=80&w=400",
    isbn: "978-0-06-291659-4",
    pages: 352,
    binding: "Hardcover",
    publisher: "Harper",
    dimensions: "15.2 x 22.8 cm",
    rating: 4.7,
    featured: true,
    bgAccent: "#f3c63f",
    description: "Innovation is the main event of the modern age, the reason we experience dramatic increases in our living standards. Yet we understand it far less than we think.",
    authorBio: "Matt Ridley is the award-winning author of several books, including The Red Queen, Genome, and The Rational Optimist.",
    specifications: {
      "Format": "Hardback"
    },
    reviews: []
  },
  {
    id: "company-of-one",
    title: "Company of One",
    subtitle: "Why Staying Small is the Next Big Thing for Business",
    author: "Paul Jarvis",
    category: "Business",
    price: 18.20,
    publishDate: "January 2019",
    coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=400",
    isbn: "978-1-328-97235-4",
    pages: 272,
    binding: "Hardcover",
    publisher: "Houghton Mifflin Harcourt",
    dimensions: "13.9 x 21.0 cm",
    rating: 4.6,
    featured: true,
    bgAccent: "#93a2b0",
    description: "What if the real key to a richer and more satisfying career is and stays as a company of one?",
    authorBio: "Paul Jarvis is a designer and writer who has worked for himself for over two decades with clients like Microsoft and Yahoo.",
    specifications: {
      "Format": "Hardback with jacket"
    },
    reviews: []
  },
  {
    id: "stupore-e-tremori",
    title: "Stupore E Tremori",
    subtitle: "Fear and Trembling / Stupor and Tremblings",
    author: "Amélie Nothomb",
    category: "Drama",
    price: 14.50,
    publishDate: "August 1999",
    coverImage: "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&q=80&w=400",
    isbn: "978-2-226-10903-4",
    pages: 192,
    binding: "Softcover",
    publisher: "Albin Michel",
    dimensions: "12.0 x 18.5 cm",
    rating: 4.9,
    featured: true,
    bgAccent: "#7a312a",
    description: "A brilliant, sharp-tongued, semi-autobiographical satire of corporate culture and traditional structure inside a highly demanding Japanese conglomerate.",
    authorBio: "Amélie Nothomb is a prolific Belgian novelist who spent part of her childhood and early professional life in Japan.",
    specifications: {
      "Format": "Paperback"
    },
    reviews: []
  },
  {
    id: "the-bees",
    title: "The Bees",
    subtitle: "A Novel",
    author: "Laline Paull",
    category: "Sci-Fi",
    price: 17.00,
    publishDate: "May 2014",
    coverImage: "https://images.unsplash.com/photo-1532012197267-da84d127e765?auto=format&fit=crop&q=80&w=400",
    isbn: "978-0-06-233117-5",
    pages: 352,
    binding: "Softcover",
    publisher: "Harper",
    dimensions: "13.5 x 20.3 cm",
    rating: 4.5,
    featured: false,
    description: "An extraordinary thriller set in a beehive, detailing a worker bee who must protect her sacred hive against overwhelming systemic stakes.",
    authorBio: "Laline Paull is a screenwriter and novelist. She studied English at Oxford, screenwriting in Los Angeles, and theater in London.",
    specifications: { "Format": "Paperback" },
    reviews: []
  },
  {
    id: "real-help",
    title: "Real Help",
    subtitle: "Honest Advice on Income, Self-Discipline, and Survival",
    author: "Ayodeji Awosika",
    category: "Education",
    price: 15.99,
    publishDate: "January 2020",
    coverImage: "https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=400",
    isbn: "978-1-7343467-0-1",
    pages: 212,
    binding: "Softcover",
    publisher: "Awosika Media",
    dimensions: "15.0 x 22.8 cm",
    rating: 4.8,
    featured: false,
    description: "Real Help is a book for people who want to succeed but are tired of the cheesy, magical-thinking self-help strategies of the past.",
    authorBio: "Ayodeji Awosika is a personal development writer, speaker, and digital consultant who speaks truthfully on habits and creation.",
    specifications: { "Format": "Paperback" },
    reviews: []
  },
  {
    id: "the-fact-of-a-body",
    title: "The Fact of a Body",
    subtitle: "A Murder and a Memoir",
    author: "Alexandria Marzano-Lesnevich",
    category: "Drama",
    price: 16.99,
    publishDate: "May 2017",
    coverImage: "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&q=80&w=400",
    isbn: "978-1-250-13769-2",
    pages: 326,
    binding: "Hardcover",
    publisher: "Flatiron Books",
    dimensions: "14.5 x 21.5 cm",
    rating: 4.7,
    featured: false,
    description: "A mesmerizing and profound exploration of a young lawyer who finds her core beliefs challenged when she assists on a murder defense case.",
    authorBio: "Alexandria Marzano-Lesnevich is an assistant professor of English at Bowdoin College and a recipient of a National Endowment for the Arts fellowship.",
    specifications: { "Format": "Hardcover" },
    reviews: []
  },
  {
    id: "the-room",
    title: "The Room",
    subtitle: "A Novel of Office Absurdity",
    author: "Jonas Karlsson",
    category: "Fantasy",
    price: 14.95,
    publishDate: "April 2014",
    coverImage: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=400",
    isbn: "978-0-8041-3838-3",
    pages: 192,
    binding: "Softcover",
    publisher: "Hogarth",
    dimensions: "12.8 x 19.8 cm",
    rating: 4.4,
    featured: false,
    description: "An eccentric, hilarious Swedish office novel about an employee who finds a secret room in his corporate headquarters that nobody else seems to see.",
    authorBio: "Jonas Karlsson is one of Sweden's most prominent actors and an acclaimed writer of short fiction and theater plays.",
    specifications: { "Format": "Paperback" },
    reviews: []
  },
  {
    id: "through-the-window",
    title: "Through the Window",
    subtitle: "Silent Records of Travel & Design",
    author: "Cate Edmonds",
    category: "Geography",
    price: 22.00,
    publishDate: "June 2021",
    coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=400",
    isbn: "978-1-7893-8012-4",
    pages: 240,
    binding: "Softcover",
    publisher: "Global Nomad Publishing",
    dimensions: "15.0 x 21.0 cm",
    rating: 4.6,
    featured: false,
    description: "A poetic journal showcasing the design choices and cultural observations across European train windows and historical hotels.",
    authorBio: "Cate Edmonds is a travel diary illustrator and geographical researcher living between London and Geneva.",
    specifications: { "Format": "Limp-bound paperback" },
    reviews: []
  },
  {
    id: "grid-system",
    title: "Grid Systems in Graphic Design",
    subtitle: "A Visual Guide for Architectural Page Design",
    author: "Josef Müller-Brockmann",
    category: "Art & Design",
    price: 68.00,
    publishDate: "March 2024",
    coverImage: "https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=600",
    isbn: "978-3-7212-0145-1",
    pages: 356,
    binding: "Linen-bound Hardcover",
    publisher: "The Library Press in cooperation with Atelier Zürich",
    dimensions: "21.0 x 29.7 cm (A4)",
    rating: 4.9,
    featured: true,
    curatedCollection: "Archival Series & Limited Editions",
    description: "The definitive manual on typographic grids. This volume stands as a testament to Swiss editorial precision, setting the foundational rules for structured visual hierarchy, spatial density, and proportional alignment across books, monographs, and newspapers.",
    authorBio: "Josef Müller-Brockmann (1914–1996) was a pioneer of Swiss Style typography. He studied graphic design and history of art in Zürich and worked as an independent designer, theorist, and educator.",
    specifications: {
      "Paper Stock": "170gsm Arctic Volume Silk, ultra-white",
      "Typefaces": "Haas Grotesk, Neue Haas Grotesk Bold",
      "Spine Stitching": "exposed Smyth sewing with contrasting charcoal thread",
      "Print Run": "First edition, 1500 hand-numbered copies",
    },
    reviews: [
      {
        id: "r1",
        author: "Marcus Aurelius V",
        rating: 5,
        date: "April 12, 2026",
        comment: "This book is a sacred object. The linen binding details are flawless. Standard delivery arrived in pristine condition within three days.",
      },
      {
        id: "r2",
        author: "Dr. Elena Rostova",
        rating: 5,
        date: "May 01, 2026",
        comment: "A magnificent monograph. The ink saturation on the heavy silk pages brings Swiss typography to life in my studio library.",
      }
    ],
    insidePages: [
      "No. 1 — THE LAWS OF RATIO\n\nTo construct a grid is to divide space into smaller units of visual responsibility. In this chapter, we outline the mathematical intervals of A4 paper stock, detailing how margins of 24mm coordinate with 3-column structural baselines.",
      "No. 2 — TYPOGRAPHIC SCALE\n\nType must seek architectural stability. We advocate for a strictly geometric hierarchy:\n\n- Header: 36pt Helvetica, tight letterspacing\n- Body: 10pt / 14pt auto leading\n- Margins: 8pt mono captions",
      "No. 3 — COGNITIVE SPACE\n\nWhitespace is not passive canvas. It is active guidance. By restricting the typographic payload to exactly 52% of the physical field area, the observer finds silent focus, enabling faster synthesis of form."
    ]
  },
  {
    id: "structures-silence",
    title: "Structures of Silence",
    subtitle: "Monoliths, Concrete, and Natural Illumination",
    author: "Tadao Ando & Kengo Kuma",
    category: "Architecture",
    price: 85.00,
    publishDate: "November 2025",
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=600",
    isbn: "978-4-8842-3091-8",
    pages: 420,
    binding: "Exposed Board Hardcover",
    publisher: "Atelier Tokyo Monographs",
    dimensions: "24.5 x 30.0 cm",
    rating: 4.8,
    featured: true,
    curatedCollection: "Archival Series & Limited Editions",
    description: "An intimate, photographic registry of contemporary Japanese monolithic concrete structures and light-wells. Includes full, high-contrast black-and-white plates documenting the dramatic passage of daylight across raw materials.",
    authorBio: "Tadao Ando and Kengo Kuma represent the pinnacle of modern architectural philosophy in East Asia, crafting sacred, minimalist spaces that dialogue deeply with light and localized environments.",
    specifications: {
      "Paper Stock": "190gsm Munken Kristall Rough, uncoated matte",
      "Plates": "76 duotone analog photography reproductions",
      "Cover Treatment": "De-embossed concrete texture on heavyweight gray fiber boards",
      "Language Options": "Dual English / Japanese translation",
    },
    reviews: [
      {
        id: "r3",
        author: "Søren K.",
        rating: 5,
        date: "February 24, 2026",
        comment: "The photo plates are unbelievably sharp. You can almost feel the cold grit of the concrete wall surface.",
      }
    ],
    insidePages: [
      "CHAPTER 2 — INTERVALS OF WOOD AND SUN\n\n'In light, concrete finds its soul. Shadows behave not as dark stains, but as solid volumes that stretch across the floor plane, dividing the room chronologically indexical.'",
      "CHAPTER 8 — SACRED SHEDS\n\nWe present nine shrines of concrete, constructed between 1988 and 2021. In each example, structural framework voids are positioned facing direct solar headings to construct temporary halos of morning moisture."
    ]
  },
  {
    id: "ateliers-sanctuary",
    title: "Atelier & Sanctuary",
    subtitle: "Inside the Creative Sacred Workspaces of Europe",
    author: "Henri de Saint-Sulpice",
    category: "Art & Design",
    price: 45.00,
    publishDate: "January 2026",
    coverImage: "https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?auto=format&fit=crop&q=80&w=600",
    isbn: "978-2-07-012942-0",
    pages: 280,
    binding: "Perfect Bound Softcover with French Flaps",
    publisher: "Atelier Paris",
    dimensions: "18.0 x 24.0 cm",
    rating: 4.7,
    featured: false,
    curatedCollection: "Archival Series & Limited Editions",
    description: "A rare peek into the preservation of artistic enclaves across France, Belgium, and Italy. Highlighting the wooden desks, dust motes, dried inks, and pristine work-tables that fostered modern existentialist paintings.",
    authorBio: "Henri de Saint-Sulpice is an architectural historian and curator based in Lyon. He spent four years documenting rural workspaces in western Europe.",
    specifications: {
      "Paper Stock": "130gsm FSC recycling amber tint paper",
      "Binding Thread": "French-fold linen stitch",
      "Total Plates": "104 architectural interior profiles",
    },
    reviews: [],
    insidePages: [
      "M. DELAUNAY'S LOFT — Lyon, 1928\n\nThe paint brushes are stacked upright inside heavy stoneware jugs. To our left, a singular Northern window lets in a cold, blue daylight that remains unaffected by the afternoon sun.",
      "THE COOPERATIVE CELL — Florence, 1947\n\nSix woodblock carvers operated this narrow workspace. We note how the pine workbenches have been worn smooth at the corners, polished by forty years of resting elbows."
    ]
  },
  {
    id: "philosophy-forms",
    title: "The Philosophy of Forms",
    subtitle: "Symmetry, Ontology, and Bauhaus Geometry",
    author: "Dr. Walter Genz",
    category: "Philosophy",
    price: 54.00,
    publishDate: "May 2025",
    coverImage: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&q=80&w=600",
    isbn: "978-3-86335-512-1",
    pages: 310,
    binding: "Linen-bound Hardcover with slipcase",
    publisher: "The Library Press in cooperation with Leipzig Academic",
    dimensions: "16.0 x 23.5 cm",
    rating: 4.6,
    featured: false,
    curatedCollection: "Philosophical Inquiry",
    description: "An intensive debate linking Platonic solids with industrial design constraints of the mid-20th century. Genz details how the circle, triangle, and square evolved from mystical symbols of deity into rational components of functional chairs and architectural profiles.",
    authorBio: "Dr. Walter Genz teaches aesthetic theory at Heidelberg. He has published extensively on modern structuralist epistemology.",
    specifications: {
      "Slipcase": "Heavyweight 2000gsm grey pulpboard with black hot-foil stamp",
      "Paper": "115gsm Salzer EOS offset book cream",
      "Ribbon": "woven dark red cotton bookmark attached",
    },
    reviews: [],
    insidePages: [
      "SECTION I — THE MORAL CIRCLE\n\nIs there an ethics to the arc? When Kandinsky positioned a glowing yellow sphere over an ink-blue background, he was not executing decoration. He initiated an inquiry into the weights of heavy souls.",
      "SECTION IV — BEYOND UTILITY\n\nBauhaus did not proclaim the death of beauty; it proclaimed the merging of beauty into the structural bones of everyday utility. In this segment, we examine the tubular steel desk chairs of Dessau."
    ]
  },
  {
    id: "quiet-geometry",
    title: "A Quiet Geometry",
    subtitle: "Poems on Light, Space, and the Passing of Seasons",
    author: "Sylvia Vance",
    category: "Poetry",
    price: 28.00,
    publishDate: "April 2026",
    coverImage: "https://images.unsplash.com/photo-1476275466078-4007374efbbe?auto=format&fit=crop&q=80&w=600",
    isbn: "978-1-101-94752-1",
    pages: 124,
    binding: "Hand-Stitched Softcover with Deckled Edges",
    publisher: "Atelier Books Poetry",
    dimensions: "14.0 x 20.0 cm",
    rating: 4.9,
    featured: true,
    curatedCollection: "Philosophical Inquiry",
    description: "A gorgeous collection of minimalist poems dealing with local coordinates, the cold texture of limestone hearths, and the geometry of afternoon shadows tracing across blank walls.",
    authorBio: "Sylvia Vance is a contemporary poet residing in the coastal islands of Scotland. This is her third collection, written during a winter period of silent retreat.",
    specifications: {
      "Cover Stock": "320gsm Gmund Cotton, tactile textured",
      "Production": "Hand-stitched in limited runs of 500 copies",
      "Typography": "Set in Garamond Italic",
    },
    reviews: [
      {
        id: "rv1",
        author: "Julian G.",
        rating: 5,
        date: "May 10, 2026",
        comment: "Words that settle like fine dust in a perfectly silent gallery. The paper's deckled margin adds an incredible artisanal touch.",
      }
    ],
    insidePages: [
      "POEM III — RADIAL INTERVALS\n\n\n\n\n      A slate floor holds the cold\n      until noon.\n      \n      Then, an angle of white glare\n      cuts the fireplace stone\n      into two clean, silent triangles.\n      \n      One remains night,\n      the other: brief salt.",
      "POEM XVII — RECTANGLES\n\n\n\n\n      We have framed the forest\n      with local cedar,\n      \n      locking its green sway\n      into four neat panels of double glass.\n      \n      Now, the wild pines appear\n      as curated paintings\n      waiting for a slow collector's appraisal."
    ]
  },
  {
    id: "modern-shrines",
    title: "Modern Shrines & Monoliths",
    subtitle: "Brutalist Desolation and Sacred Havens",
    author: "Prof. Arthur Pendelton",
    category: "Architecture",
    price: 72.00,
    publishDate: "September 2025",
    coverImage: "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=600",
    isbn: "978-0-300-24718-4",
    pages: 340,
    binding: "Linen-bound Hardcover",
    publisher: "Oxford Design Editions",
    dimensions: "22.0 x 28.0 cm",
    rating: 4.5,
    featured: false,
    curatedCollection: "Archival Series & Limited Editions",
    description: "An intensive study of architectural gigantism and brutalist materials that somehow manage to establish safe, sacred spatial quietude. From high-altitude mountain lookouts in Yugoslavia to minimal concrete vaults in Brazil.",
    authorBio: "Arthur Pendelton is a professor of architectural history and theory, specializing in brutalist structures and concrete preservation movements.",
    specifications: {
      "Paper Class": "150gsm Symbol Card, matte-varnished",
      "Stitched Spine": "Hardback head-and-tail bands in charcoal linen",
      "Detail Work": "Blind-debossed title layout on cover cloth",
    },
    reviews: [],
    insidePages: [
      "III. SACRED EXCLUSION — SÃO PAULO\n\nBy sinking the main floor plane three meters below the level of the sidewalk, the architects isolated the sanctuary from the heavy diesel hum of urban transit, transforming grey concrete into a canyon of meditative relief.",
      "IX. THE HIGH BEACONS\n\nAbove the snowline, monolithic monuments command the sky. They do not request tourists; they perform as massive sundials, recording the slow tilt of the earth against silent basalt crags."
    ]
  },
  {
    id: "minimalist-typographic",
    title: "Minimalist Typographic Form",
    subtitle: "The Aesthetic of Restraint in European Print",
    author: "Jan Tschichold (Critical Edition)",
    category: "Art & Design",
    price: 58.00,
    publishDate: "October 2024",
    coverImage: "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&q=80&w=600",
    isbn: "978-3-12-421040-0",
    pages: 224,
    binding: "Hardback in Japanese Paper Cover",
    publisher: "Atelier Basel Monographs",
    dimensions: "17.0 x 24.5 cm",
    rating: 4.8,
    featured: false,
    curatedCollection: "Archival Series & Limited Editions",
    description: "A clean critique of the 'new typography' era, exploring the removal of ornamental clutter. The book focuses on asymmetry, white space, and why the selection of appropriate leading (line-spacing) constitutes a moral imperative in visual culture.",
    authorBio: "Jan Tschichold (1902–1974) was an iconic German theoretician, typographer, and teacher. His text 'Die neue Typographie' laid the foundations for the modern clean layout layout design.",
    specifications: {
      "Covering": "Fine structural mulberry Japanese paper over stiff grey boards",
      "Binding": "Smyth sewn with raw cotton cord",
      "Edition": "Limited translation, 2000 numbered volumes",
    },
    reviews: [],
    insidePages: [
      "THESIS V — THE VOID IS AN INSTRUMENT\n\n'Decorations are a confession of fear. He who cannot justify his words with simple black characters on a clear canvas hides behind golden floral borders. Strip the ornaments; show the naked structure of the dialogue.'"
    ]
  },
  {
    id: "epistles-silent-mind",
    title: "Epistles to the Silent Mind",
    subtitle: "Stoicism, Spatial Restraint, and the Shaker Legacy",
    author: "Brother Thomas Merton Jr.",
    category: "Philosophy",
    price: 36.00,
    publishDate: "April 2025",
    coverImage: "https://images.unsplash.com/photo-1543002588-bfa74002ed7e?auto=format&fit=crop&q=80&w=600",
    isbn: "978-0-8041-3811-6",
    pages: 198,
    binding: "Linen-bound Hardcover",
    publisher: "The Library Press in cooperation with Kentucky Monastic",
    dimensions: "13.0 x 19.5 cm",
    rating: 4.9,
    featured: false,
    curatedCollection: "Philosophical Inquiry",
    description: "An incredibly beautiful treatise connecting silent stoic practices with the functional carpentry of Shaker communities. Merton shows how perfect rectangular boxes, peg rails, and wooden chairs are spiritual exercises transformed into timber structures.",
    authorBio: "Brother Thomas Merton Jr. was a contemplative scholar who dedicated his late career to the documentation of functional craftsmanship.",
    specifications: {
      "Fabric Spines": "Warm oatmeal natural linen weave",
      "Endpapers": "Italian acid-free marbled papers",
      "Typography": "Set in Bembo, 11 on 15pt lead",
    },
    reviews: [
      {
        id: "rm1",
        author: "A. Finch",
        rating: 5,
        date: "March 3, 2026",
        comment: "Outstanding text. A blueprint for simple living. The book looks extremely handsome resting on my ash table.",
      }
    ],
    insidePages: [
      "EPISTLE IV — THE SACRED BEVEL\n\n'In the shaving of a pine board, there is a liturgy. If the edge is planed true, it sits against its neighbor without gap or metal nails. In this tightly joined seam, the carpenter has made room for peace.'"
    ]
  }
];

export const MOCK_USER: UserProfile = {
  name: "Arthur Pendelton",
  email: "a.pendelton@oxford-press.org",
  phoneNumber: "+44 20 7946 0912",
  membershipTier: "Archivist",
  joinedDate: "September 2024",
  shippingAddress: {
    fullName: "Prof. Arthur Pendelton",
    email: "a.pendelton@oxford-press.org",
    address: "Room 402, High Street Quads",
    city: "Oxford",
    postalCode: "OX1 4JD",
    country: "United Kingdom",
  }
};

export const MOCK_ORDERS: Order[] = [
  {
    id: "ORD-2026-8941",
    date: "May 18, 2026",
    items: [
      {
        book: BOOKS[0], // Grid Systems in Graphic Design
        quantity: 1
      },
      {
        book: BOOKS[4], // A Quiet Geometry
        quantity: 2
      }
    ],
    total: 124.00,
    status: "Processing",
    shippingAddress: MOCK_USER.shippingAddress,
    discountApplied: {
      code: "LAUNCH15",
      amount: 19.40
    }
  },
  {
    id: "ORD-2025-4123",
    date: "December 04, 2025",
    items: [
      {
        book: BOOKS[1], // Structures of Silence
        quantity: 1
      }
    ],
    total: 85.00,
    status: "Delivered",
    shippingAddress: MOCK_USER.shippingAddress
  }
];
